In [1]:
import scipy.io
import pandas as pd
import numpy as np

In [2]:
mat = scipy.io.loadmat('../dataset/qm7.mat')

In [3]:
mat = {k:v for k, v in mat.items() if k[0] != '_'}

In [4]:
print(mat.keys())

dict_keys(['X', 'R', 'Z', 'T', 'P'])


In [5]:
print(mat['X'].shape, mat['T'].shape, mat['P'].shape, mat['Z'].shape, mat['R'].shape)

(7165, 23, 23) (1, 7165) (5, 1433) (7165, 23) (7165, 23, 3)


In [6]:
print(mat['R'])

[[[ 1.8864380e+00 -4.6487264e-03 -8.2392059e-03]
  [ 3.9499245e+00 -4.5920345e-03  7.8234663e-03]
  [ 1.1976895e+00  1.9404842e+00  7.8234663e-03]
  ...
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]

 [[ 1.8973607e+00 -5.5746920e-03 -1.2094247e-02]
  [ 4.7544756e+00 -1.3265877e-02  1.1149384e-03]
  [ 1.1760710e+00  1.9320560e+00 -3.0991510e-03]
  ...
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]

 [[ 1.8692415e+00  1.8897261e-04  0.0000000e+00]
  [ 4.3934622e+00 -3.2125344e-04 -0.0000000e+00]
  [ 8.1146729e-01  1.7577099e+00  0.0000000e+00]
  ...
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]

 ...

 [[ 4.1100221e+00 -1.0346062e+00  2.6948628e+00]
  [ 4.3785710e+00  6.1529484e-02  4.884

In [9]:
# print out the shape of the first R matrix.
print(mat['R'][:1])

[[[ 1.886438   -0.00464873 -0.00823921]
  [ 3.9499245  -0.00459203  0.00782347]
  [ 1.1976895   1.9404842   0.00782347]
  [ 1.1849339  -0.99726516  1.6593875 ]
  [ 1.2119948  -0.9589793  -1.710958  ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]]


In [8]:
print(mat['T'])

[[ -417.96  -712.42  -564.21 ... -1662.1  -1782.01 -1919.  ]]


In [ ]:
data = pd.DataFrame({k: pd.Series(v[0]) for k, v in mat.iteritems()})
data.to_csv("example.csv")