<a href="https://colab.research.google.com/github/Nov05/DS5-kaggle-scalar-coupling/blob/master/notebooks/nov05_visual_2019_07_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# created by nov05 on 2019-07-28
# DS5-kaggle-scalar-coupling
# notebooks

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
!pip install --upgrade ase
# Successfully installed ase-3.18.0
# you might need to restart the runtime

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
import zipfile
import glob
import os
import gc
import random

import ase
from ase import Atoms
import ase.visualize

competition_name = "champs-scalar-coupling"
path_data = "/content/drive/My Drive/data/"
path_molecular = path_data + "kaggle-molecular/"
path_structures = path_molecular + "structures/"

https://www.kaggle.com/borisdee/how-to-easy-visualization-of-molecules  

In [3]:
structures = pd.read_csv(path_molecular+'structures.csv')
print(structures.shape)
structures.head(2)

(2358657, 6)


molecule_name  atom_index atom         x         y         z
0  dsgdb9nsd_000001           0    C -0.012698  1.085804  0.008001
1  dsgdb9nsd_000001           1    H  0.002150 -0.006031  0.001976

In [4]:
molecule = random.choice(structures['molecule_name'].unique())
molecule = structures[structures['molecule_name']==molecule]
molecule

molecule_name  atom_index atom         x         y         z
13559  dsgdb9nsd_001114           0    C -0.162005  1.502716 -0.037131
13560  dsgdb9nsd_001114           1    C  0.162628  0.015612  0.001942
13561  dsgdb9nsd_001114           2    O  1.282968 -0.420389  0.035674
13562  dsgdb9nsd_001114           3    N -0.991050 -0.785911 -0.005948
13563  dsgdb9nsd_001114           4    C -1.071024 -2.188149  0.022466
13564  dsgdb9nsd_001114           5    C -2.508686 -2.689281  0.002720
13565  dsgdb9nsd_001114           6    O -0.113353 -2.914754  0.058635
13566  dsgdb9nsd_001114           7    H  0.772522  2.061983 -0.029109
13567  dsgdb9nsd_001114           8    H -0.728298  1.756178 -0.939973
13568  dsgdb9nsd_001114           9    H -0.766272  1.794314  0.828833
13569  dsgdb9nsd_001114          10    H -1.871114 -0.293532 -0.035558
13570  dsgdb9nsd_001114          11    H -3.029453 -2.349821 -0.899282
13571  dsgdb9nsd_001114          12    H -2.496688 -3.778134  0.023705
13572  dsgdb9nsd_001114          13    H -3.064898 -2.316318  0.869670

In [5]:
# get atom coordinates
atoms = molecule.iloc[:, 3:].values
print(atoms)

[[-1.62005117e-01  1.50271633e+00 -3.71308094e-02]
 [ 1.62628345e-01  1.56118905e-02  1.94190000e-03]
 [ 1.28296832e+00 -4.20389494e-01  3.56741935e-02]
 [-9.91049534e-01 -7.85911150e-01 -5.94827410e-03]
 [-1.07102401e+00 -2.18814933e+00  2.24657291e-02]
 [-2.50868580e+00 -2.68928119e+00  2.72044100e-03]
 [-1.13352864e-01 -2.91475433e+00  5.86346631e-02]
 [ 7.72522210e-01  2.06198324e+00 -2.91085300e-02]
 [-7.28298390e-01  1.75617826e+00 -9.39973131e-01]
 [-7.66272083e-01  1.79431435e+00  8.28832667e-01]
 [-1.87111378e+00 -2.93531811e-01 -3.55581130e-02]
 [-3.02945274e+00 -2.34982098e+00 -8.99282052e-01]
 [-2.49668794e+00 -3.77813426e+00  2.37048753e-02]
 [-3.06489848e+00 -2.31631821e+00  8.69670311e-01]]


In [6]:
# Get atomic symbols
symbols = molecule.iloc[:, 2].values
print(symbols)

['C' 'C' 'O' 'N' 'C' 'C' 'O' 'H' 'H' 'H' 'H' 'H' 'H' 'H']


In [8]:
system = Atoms(positions=atoms, symbols=symbols)
ase.visualize.view(system, viewer="x3d")